const {MessageEmbed} = require('discord.js')

module.exports.run = async (bot, message, args) => {
  let name = args.slice(1).join(" ")
  const semperm = new MessageEmbed()
    .setTitle("Erro")
    .setDescription(`Parece que você não tem permissão para alterar os nicknames.`)
    .setColor('RED')
    .setFooter('${author.nickname}', message.author.displayAvatarURL())
  if(!message.member.permissions.has("MANAGE_NICKNAMES")) return message.reply(semperm)
  const quemmudar = new MessageEmbed()
    .setTitle("**Alterar**")
    .setDescription("**Como Usar**:\n\n`Rf!alterar @Usuario Legal#0007 Pessoinha`")
   .setColor('RED')
    .setFooter('${author.nickname}', message.author.displayAvatarURL())
  if (!args[0])return message.channel.send(quemmudar)
  const User = message.mentions.members.first() || message.guild.members.cache.get(args[0]) || message.member;
  if (!User) return message.channel.send(quemmudar)
  if(!name){
    const nickname = new MessageEmbed()
    .setTitle("**Alterar**")
    .setDescription("**Como Usar**:\n\n`Rf!alterar @Usuario Legal#0007 Pessoinha`")
    .setColor('RED')
    .setFooter('Opan', message.author.displayAvatarURL())
    return message.channel.send(nickname)
  }
      const naoposso = new MessageEmbed()
    .setTitle("Erro")
    .setDescription(`Eu não posso alterar o nickname de quem tem permissão de administrador no servidor.`)
    .setColor('RED')
    .setFooter('Opan', message.author.displayAvatarURL())
  if (!User.manageable) return message.channel.send(naoposso)
  User.setNickname(name)
  const embed = new MessageEmbed()
  .setDescription('Apelido alterado')
  .setColor('GREEN')
  .setFooter('Opan', message.author.displayAvatarURL())
  message.reply(embed)
}